### ISSUE TITLE
Improve example and documentation 

### ISSUE THREAD

**Issue by lukassgramm** [imsujan276/shopify_flutter#31]
Missing from the example or documentation are the following steps that can help a developer understand the use of the package:

- Adding a product or variant to orders
- Proceed with payment
- Also in the example is an email that does not end with an authorized domain such as gmail.com and therefore the purchase will fail, from shopify you cannot even create an order with that domain.

If needed I can help contribute (for free) to the documentation after an explanation of the functions, to improve this fantastic package.

**Comment by imsujan276** [comment]
Thank you so much for this.  I would really appreciate the help.

As for your query.

**1. Adding a product or variant to checkout**
- when the user tries to add a product to the cart for the first time, 
    - create a checkout by calling `createCheckout()` from `ShopifyCheckout.instance` by providing email and mailing address.
    -  call `addLineItemsToCheckout()` to add the product as line item. Create a line items by providing the product title, id, variant id and quantity.
   
- You can update or remove the line item from the checkout by calling `updateLineItemsInCheckout` and `removeLineItemsFromCheckout`
- All these `addLineItemsToCheckout`, `updateLineItemsInCheckout` and `removeLineItemsFromCheckout` takes the same parameters.

- if you want to update the checkout user email, you can call `updateCheckoutEmail`

- If you already have the checkout id stored, you can get the checkout info by calling `getCheckoutInfoQuery`
- Update the checkout shipping address by using `shippingAddressUpdate` and provide checkout id and address.

<hr>

**2. Proceed with payment**
- We use webview to proceed with the checkout payment. 
- `checkout.webUrl` us used to open the checkout page and proceed with payment. 
- Example
``` dart
class WebViewCheckout extends ConsumerStatefulWidget {
  static route(Checkout checkout) =>
      MaterialPageRoute(builder: (_) => WebViewCheckout(checkout));
  final Checkout checkout;
  const WebViewCheckout(this.checkout, {super.key});

  @override
  ConsumerState<ConsumerStatefulWidget> createState() =>
      _WebViewCheckoutState();
}

class _WebViewCheckoutState extends ConsumerState<WebViewCheckout> {
  late final InAppWebViewController webViewController;

  @override
  void initState() {
    super.initState();
  }

  void handleUrlChanged(String url) {
    if (url.contains('/order-received/') ||
        url.contains('checkout/success') ||
        url.contains('thank-you') ||
        url.contains('thank_you')) {
      Future.delayed(const Duration(seconds: 2), () {
        Navigator.pop(context, true);
      });
    }
    if (url.contains('/member-login/')) {
      showSnackbar('Unauthorized User');
      Navigator.pop(context);
    }
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          title: const Text('Checkout'),
        ),
        // body: WebViewWidget(controller: controller)
        body: InAppWebView(
          initialUrlRequest: URLRequest(
            url: Uri.parse(widget.checkout.webUrl!),
          ),
          onWebViewCreated: (controller) {
            webViewController = controller;
          },
          onUpdateVisitedHistory: (controller, url, androidIsReload) {
            if (url != null) handleUrlChanged(url.toString());
          },
        ),
      ),
    );
  }
}

```

<hr>

**3. invalid email in example.**
Since it is an example, I just used a demo showing you can pass email addresses too. It does not need to be random. In real app, we will be using real email addresses.
