### ISSUE TITLE
Disable cache

### ISSUE THREAD

**Issue by miltonlm** [imsujan276/shopify_flutter#39]
Hi all,

I query collections initially and it comes updated but after the first request all data comes from a cache, it is needed that we disable cache for this specific application, we require it updated every minute so the user does not have to close the app to see latest changes.
Can any of you help me with this? I am willing to make a pull request including the option to disable cache globally.

**Comment by imsujan276** [comment]
Thank you for raising this issue.

In most cases, cache helps from overflowing the shopify api request by caching it. That's why it is added by default.

Currently I am too tight in my work so I may not be able to do the update for few days.

You are welcome to male the update. But instead of removing it completely, you could make it optional by sending a flag. Which by default uses the cache.

**Comment by imsujan276** [comment]
v1.5.6 has an option to pass a cache policy that defines the query requests caching mechanism.
