### ISSUE TITLE
Metafields not getting fetched

### ISSUE THREAD

**Issue by miltonlm** [imsujan276/shopify_flutter#40]
I have the latest version 1.5.5 but metafields is always an empty list. After checking the code I can see that the graphql query string does not include the **metafields** field in it.

lib/graphql_operations/storefront/queries/get_all_products_from_collection_by_id.dart:2

Can any of you help me? I am also willing to create a pull request for this.
Thanks.

**Comment by imsujan276** [comment]
Hello @miltonlm 

You are open to create a pull request for this

**Comment by reesz** [comment]
I'm running into the same issue.
I see that `product.freezed.dart` has some commented out code for metafields (`line 147`, `line 292+`)
Also `product.dart:392`

@imsujan276 can you share some insights into why this code is not in use? What made you drop it? 

Might help someone who wants to create a PR to understand if they can build on that/what needs to be looked at, or if it's better to start from scratch.

**Comment by imsujan276** [comment]
@reesz The metafields is removed from the products because we have not implemented the metafields in the grapgql query. Also, one of the issue was the metafields need a custom identifier to be passed which not all the store may not have. so for the time being, we have removed this property.

But you are open to create a PR for this.
