### ISSUE TITLE
Selling Plan Allocation in Cart/Checkout

### ISSUE THREAD

**Issue by abubakarflutter** [imsujan276/shopify_flutter#41]
First of all, thank you for this awesome package, I really love it.

I've integrated Recharge App in my Shopify App, where user can buy in installments or recurring. 
As far I've noticed from web page its being fetched under **selling_plan_allocation**  object,

You can read more about it here, from Shopify Page - [Selling Plan Allocation](https://shopify.dev/docs/api/liquid/objects/selling_plan_allocation)

I really need of it to integrate in my app, so would you please add this, thank you

**Comment by imsujan276** [comment]
[Selling Plan Allocation](https://shopify.dev/docs/api/liquid/objects/selling_plan_allocation) is pretty new to me. I have tried running the query to get the selling_plan_allocation from the product variant but I am always getting null. 

I'm not sure if it needs some extra configurations.

Could you share me with the steps to setup the store so that I will get the selling_plan_allocation data?
